Update aplication-model sheets
Flexberry/ember-flexberry-designer pull request #538
Opened 2019-10-23 05:12 UTC by s-andrey

2019-10-25 11:34 UTC, bratchikov requested changes
Проверил первые 3 файла. Для начала отформатируй yui-doc описание параметров, методов и т.п. Они должны быть с большой буквы, а в конце точка.

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-base-sheet.js
> +    Service for managing the state of the component.
Выше комментарий такой же точно.

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-base-sheet.js
> +    Flag: indicates whether property is readonly.
Может быть "sheet is readonly".

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-base-sheet.js
> +     @param {String} sheetName Sheet's dbName
Точки в конце описаний параметров. Тут и далее.

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-base-sheet.js
> +     @param {String} sheetName Sheet's dbName
При чём тут dbName?

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-class-sheet.js
> +  updateClassModel(modelselectedValue) {
modelselectedValue - Selected с большой буквы. В yui-doc нет описания параметра.

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-class-sheet.js
> +     @param {Object} model model object
С большой буквы, в конце точка.

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-class-sheet.js
> +    @param {Object} model class model.
С большой буквы.

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-class-sheet.js
> +       @param {Boolean} closeAfter close after save
С большой буквы, в конце точка.

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-diagram-sheet.js
> +     @param {Object} currentItem Current list item
Исправить

2019-10-25 11:34 UTC, bratchikov commented on addon/components/fd-sheets/fd-diagram-sheet.js
> +    @param {Object} model diagram model.
С большой буквы.

2019-10-25 17:26 UTC, bratchikov commented
@s-andrey, ты почему-то не все мои замечания исправил. См. на этой странице выше.

2019-10-28 06:21 UTC, merged

2019-10-31 05:58 UTC, s-andrey commented
#476 #535