Fix styles and icons of sidebar
Flexberry/ember-flexberry-designer pull request #812
Opened 2023-03-20 08:58 UTC by PrographerMan

2023-03-21 07:57 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> +                <i class="icon icon-fd-diagram"></i>
А это тут зачем?

2023-03-21 08:09 UTC, pepelyaeva requested changes

2023-03-21 08:09 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> +            <div class="project-name-wrapper">
Ты добавил новый класс для названия проекта, а со старым что? на нем тоже стили были. Нужно либо старые использовать либо при переименовании все старые стили удалять.
Сейчас разметка отличается от той, что была, нужно вернуть к изначальному варианту.  
![image](https://user-images.githubusercontent.com/15091209/226548271-cae427fa-7015-4f8f-8091-f42995d23519.png)

2023-03-21 09:08 UTC, pepelyaeva commented on addon/styles/addon.less
> +      content: @SyncIcon;
нужен селектор i.icon.sync.alternate:before, безотносительно кнопки, и нужно его перенести в файл [icon.overrides](https://github.com/Flexberry/ember-flexberry-designer/blob/develop/addon/styles/default/elements/icon.overrides)

2023-03-21 09:09 UTC, pepelyaeva commented on addon/styles/addon.less
> +.sidebar-sync-panel {
Все стили для сайдбара нужно перенести в файл [sidebar.overrides](https://github.com/Flexberry/ember-flexberry-designer/blob/develop/addon/styles/default/modules/sidebar.overrides)

2023-03-22 07:47 UTC, PrographerMan commented on addon/styles/addon.less
> +.sidebar-sync-panel {
Исправил

2023-03-22 07:47 UTC, PrographerMan commented on addon/styles/addon.less
> +      content: @SyncIcon;
Исправил

2023-03-22 07:47 UTC, PrographerMan commented on tests/dummy/app/templates/application.hbs
> +            <div class="project-name-wrapper">
Исправил

2023-03-22 07:52 UTC, PrographerMan commented on tests/dummy/app/templates/application.hbs
> +                <i class="icon icon-fd-diagram"></i>
Это чтобы элементы были вертикально выровнены вне зависимости от припусков и отступов в раскрытом и открытом боковом меню

2023-03-22 07:54 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> +                <i class="icon icon-fd-diagram"></i>
Я имею ввиду иконку icon-fd-diagram. на скрине видно, что там лишняя иконка добавлена

2023-03-22 07:56 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> +                <i class="icon icon-fd-diagram"></i>
Я вижу, что она там была, но из-за смены разметки она стала отображаться, это тоже исправлено?

2023-03-22 09:12 UTC, PrographerMan commented on tests/dummy/app/templates/application.hbs
> +                <i class="icon icon-fd-diagram"></i>
Да, поправил

2023-03-24 06:46 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> +                <i class="icon icon-fd-diagram"></i>
Все еще отображается
![image](https://user-images.githubusercontent.com/15091209/227445643-17d5bbd7-9305-4887-a0ae-5b6d66be5c7a.png)

2023-03-24 06:49 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> +            <div class="project-name-wrapper">
а зачем теперь две обертки для имени проекта? новые стили нельзя добавить к уже существующему классу `current-project-name`?

2023-03-24 07:18 UTC, pepelyaeva commented on addon/styles/default/elements/icon.overrides
> +@SyncIcon: "\f2f1";
Для переменных есть отдельный файл icon.variables, если такого файла нет, надо добавить и вынести переменные.

2023-03-27 10:59 UTC, PrographerMan commented on tests/dummy/app/templates/application.hbs
> +                <i class="icon icon-fd-diagram"></i>
Готово

2023-03-27 10:59 UTC, PrographerMan commented on tests/dummy/app/templates/application.hbs
> +            <div class="project-name-wrapper">
Готово

2023-03-27 10:59 UTC, PrographerMan commented on addon/styles/default/elements/icon.overrides
> +@SyncIcon: "\f2f1";
Готово

2023-03-27 11:41 UTC, pepelyaeva commented on addon/styles/default/modules/sidebar.overrides
> +  margin: 0.5rem 0 4rem 0;
Это куда идет? ты селектор .item.current-project-name удалил из разметки

2023-03-27 11:42 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> -            <i class="icon icon-fd-diagram"></i>
Удали тогда соответствующие стили тоже

2023-03-27 11:43 UTC, pepelyaeva commented on tests/dummy/app/templates/application.hbs
> -        <div class="item current-project-name">
В связи с изменениями разметки почисти стили, пожалуйста. Нужно удалить те, что больше не используются

2023-03-27 19:43 UTC, PrographerMan commented on tests/dummy/app/templates/application.hbs
> -        <div class="item current-project-name">
Готово

2023-03-27 19:43 UTC, PrographerMan commented on tests/dummy/app/templates/application.hbs
> -            <i class="icon icon-fd-diagram"></i>
Готово

2023-03-27 19:44 UTC, PrographerMan commented on addon/styles/default/modules/sidebar.overrides
> +  margin: 0.5rem 0 4rem 0;
Готово

2023-03-28 06:36 UTC, pepelyaeva commented on addon/styles/default/modules/sidebar.overrides
> -    .item {
Лишнее убрал, сейчас на мини сайдбаре текст не прячется 
![image](https://user-images.githubusercontent.com/15091209/228149080-23bc4f0d-29f2-46d7-8cef-70fb6f02b268.png)

2023-03-29 06:29 UTC, PrographerMan commented on addon/styles/default/modules/sidebar.overrides
> -    .item {
Готово
![image](https://user-images.githubusercontent.com/12534013/228445529-104712bd-e243-4a37-b5ba-9c27bdc19de8.png)

2023-03-29 07:00 UTC, pepelyaeva commented on addon/styles/default/modules/sidebar.overrides
> -    .item {
а что с выделением стало? должно быть как на скрине выше, квадратное

2023-03-29 07:01 UTC, pepelyaeva commented on addon/styles/default/modules/sidebar.overrides
> -      padding-right: 0;
вот это все надо вернуть

2023-03-29 07:17 UTC, PrographerMan commented on addon/styles/default/modules/sidebar.overrides
> -    .item {
В текущей версии дизайнера, кстати, припуски как-то странно сделаны, то есть выделение не квадратное. Теперь готово
![image](https://user-images.githubusercontent.com/12534013/228455924-c799e314-e33a-46b1-8a4a-91db07a1c143.png)

2023-03-29 07:57 UTC, pepelyaeva commented on addon/styles/default/modules/sidebar.overrides
> -    .item {
было ~40*40, сейчас 34*34

2023-03-31 07:04 UTC, PrographerMan commented on addon/styles/default/modules/sidebar.overrides
> -    .item {
Готово

2023-03-31 10:18 UTC, pepelyaeva approved these changes

2023-03-31 13:09 UTC, merged