Add mapping indication
Flexberry/ember-flexberry-designer pull request #813
Opened 2023-03-20 12:05 UTC by PrographerMan

2023-03-21 09:19 UTC, pepelyaeva requested changes

2023-03-21 09:19 UTC, pepelyaeva commented on app/templates/fd-data-types-map.hbs
> +              <a class="ui red label">Без ассоциаций</a>
Почему `<a>`? И надписи все нужно через [локали](https://github.com/Flexberry/ember-flexberry-designer/blob/develop/addon/locales/ru/forms/fd-data-types-map.js) добавлять (в en тоже), по дизайну предлагаю сделать иконку  и при наведении показывать подсказку "карточка заполнена не полностью" (Сделала цвет red с прозрачностью 0,6)
![image](https://user-images.githubusercontent.com/15091209/226562813-aeb18ea8-38e5-445d-ba58-93281901a1a1.png)

![image](https://user-images.githubusercontent.com/15091209/226558761-1bf9253a-212c-4856-9008-c9f44bacdf00.png)

2023-03-21 09:19 UTC, pepelyaeva commented on addon/controllers/fd-data-types-map.js
> +        && !isEmpty(type.sql) && !isEmpty(type.postgre) && !isEmpty(type.oracle);
Здесь предлагается оставить проверку только для c# pg и ms

2023-03-21 09:21 UTC, pepelyaeva commented on app/templates/fd-data-types-map.hbs
> +            {{#if (not dataType.hasMapping)}}
`#unless`?

2023-03-22 06:43 UTC, PrographerMan commented on addon/controllers/fd-data-types-map.js
> +        && !isEmpty(type.sql) && !isEmpty(type.postgre) && !isEmpty(type.oracle);
Исправил

2023-03-22 06:43 UTC, PrographerMan commented on app/templates/fd-data-types-map.hbs
> +              <a class="ui red label">Без ассоциаций</a>
Исправил

2023-03-24 08:20 UTC, pepelyaeva approved these changes

2023-03-24 10:29 UTC, merged