Add images for projection properties
Flexberry/ember-flexberry-designer pull request #814
Opened 2023-03-21 07:16 UTC by PrographerMan

2023-03-21 07:39 UTC, pepelyaeva requested changes

2023-03-21 07:39 UTC, pepelyaeva commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
А зачем менять на таблицу? там же вся разметка поехала

2023-03-22 05:36 UTC, PrographerMan commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
Исправил

2023-03-22 05:40 UTC, pepelyaeva commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
`<table>` остался

2023-03-24 08:38 UTC, pepelyaeva commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
Нужно вернуть выравнивание текста в атрибутах, по вертикали они должны быть на одном уровне друг с другом а также с текстом в поле Поиск. Картинку сделать такого же размера как слева. и разместить ее по центру пустого пространства
![image](https://user-images.githubusercontent.com/15091209/227467401-032ab62d-418d-4c44-921a-dee4f204eba1.png)

2023-03-27 10:35 UTC, PrographerMan commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
Исправлено

2023-03-27 11:48 UTC, pepelyaeva commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
Сейчас выглядит вот так
![image](https://user-images.githubusercontent.com/15091209/227933119-1ee56e05-dcdd-407f-a725-56ce87c606b3.png)

2023-03-27 21:42 UTC, PrographerMan commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
Теперь точно
![Screenshot_1](https://user-images.githubusercontent.com/12534013/228073461-3236765d-0284-416b-b71a-dd7e4c7fff08.png)

2023-03-28 06:43 UTC, pepelyaeva commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
ну почти 
![image](https://user-images.githubusercontent.com/15091209/228150451-18be8a2a-df06-41e5-920f-50f471131ff4.png)

2023-03-28 06:50 UTC, pepelyaeva commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
Давай вернем все отступы и разметку как было и просто  картинке absolute добавим? что за мучения)

2023-03-28 11:00 UTC, PrographerMan commented on addon/templates/components/fd-editing-panels/fd-create-view.hbs
> +      <table class="ui very basic table">
Вернул разметку и стили

2023-03-28 12:26 UTC, pepelyaeva commented on addon/styles/components/fd-create-view.less
> +      top: calc(~'50% - 16px / 2');
Все картинки разной высоты, не 16 px, поэтому некоторые картинки не выровнены по вертикали. Можно добавить обертку для картинки, сделать ее фиксированной высоты, например 20px, и внутри нее выровнять картинку по вертикали. И уже эту обертку выравнивать calc(50% - 20px / 2).

2023-03-29 13:11 UTC, pepelyaeva commented on addon/styles/components/fd-create-view.less
> +        height: 100%;
не, так они будут растянутые, надо по вертикале выровнять посередине контейнера. и 16 мало, картинка обычного атрибута 19 высотой

2023-03-31 07:02 UTC, PrographerMan commented on addon/styles/components/fd-create-view.less
> +        height: 100%;
У них фиксированная только высота, а ширина рассчитывается автоматически, чтобы выглядели пропорционально
![image](https://user-images.githubusercontent.com/12534013/229047163-7aeca7af-f738-444a-acf4-fe32cfdd0604.png)

2023-03-31 13:15 UTC, pepelyaeva commented on addon/styles/components/fd-create-view.less
> +        height: 100%;
нам пока нужно чтобы они выглядели как в дереве слева, иначе сейчас слева картинки одного размера справа другого.

2023-04-11 07:05 UTC, pepelyaeva approved these changes

2023-04-11 07:06 UTC, merged