Change master property component
Flexberry/ember-flexberry-designer pull request #815
Opened 2023-03-22 12:27 UTC by PrographerMan

2023-03-24 08:52 UTC, pepelyaeva requested changes, later dismissed
Открываю форму, добавляю лукап в представление меняю на standart, получаю пустой список в поле Свойство мастера 

![image](https://user-images.githubusercontent.com/15091209/227471003-d6252473-112d-4347-b6f0-0e90e58afa42.png)

2023-03-27 13:23 UTC, pepelyaeva commented on addon/components/fd-view-definition-item.js
> +  selectedPropertyObserver: observer('selectedProperty.lookupType', function() {
Почему через observer? Там же есть экшн changeLookupType

2023-03-27 13:46 UTC, s-andrey commented on addon/components/fd-view-definition-item.js
> +  selectedPropertyObserver: observer('selectedProperty.lookupType', function() {
тут observer норм но условие хрень, какой смысл каждый раз заново список получать при смене типа у одного и того же свойства тут надо только на selectedProperty

2023-03-27 13:46 UTC, s-andrey commented on addon/components/fd-view-definition-item.js
> +
нужны проверки что это мастер чтобы не считывать данные когда они не нужны

2023-03-27 13:46 UTC, s-andrey commented on addon/components/fd-view-definition-item.js
> +    let allAssociations = store.peekAll('fd-dev-association').filterBy('realStartRole', associationName);
вначале возьми только ассоциации из текущей стадии а уже потом фильтруй

2023-03-27 13:46 UTC, s-andrey commented on addon/components/fd-view-definition-item.js
> +    let masterProperties = allAssociations.objectAt(0).get('endClass.attributes').mapBy('name');
не objectAt(0) а firstObject мб?

2023-03-27 13:46 UTC, s-andrey commented on addon/components/fd-view-definition-item.js
> +    let masterProperties = allAssociations.objectAt(0).get('endClass.attributes').mapBy('name');
Ты проверил? Это работает с унаследованными полями?

2023-03-27 13:46 UTC, s-andrey commented on addon/components/fd-view-definition-item.js
> +      this.set('masterProperties', masterProperties);
ты проверил? так не сломается дропдаун если у класса нет атрибутов? мб если их нет надо пустой массив присваивать?

2023-03-27 14:09 UTC, pepelyaeva commented on addon/components/fd-view-definition-item.js
> +    let allAssociations = store.peekAll('fd-dev-association').filterBy('realStartRole', associationName);
На детейловой связи не работает

2023-04-11 04:32 UTC, PrographerMan commented on addon/components/fd-view-definition-item.js
> +    let allAssociations = store.peekAll('fd-dev-association').filterBy('realStartRole', associationName);
Готово

2023-04-11 04:32 UTC, PrographerMan commented on addon/components/fd-view-definition-item.js
> +      this.set('masterProperties', masterProperties);
Готово

2023-04-11 04:32 UTC, PrographerMan commented on addon/components/fd-view-definition-item.js
> +    let masterProperties = allAssociations.objectAt(0).get('endClass.attributes').mapBy('name');
Готово

2023-04-11 04:32 UTC, PrographerMan commented on addon/components/fd-view-definition-item.js
> +    let masterProperties = allAssociations.objectAt(0).get('endClass.attributes').mapBy('name');
Готово

2023-04-11 04:32 UTC, PrographerMan commented on addon/components/fd-view-definition-item.js
> +    let allAssociations = store.peekAll('fd-dev-association').filterBy('realStartRole', associationName);
Готово

2023-04-11 04:33 UTC, PrographerMan commented on addon/components/fd-view-definition-item.js
> +
Готово

2023-04-11 07:15 UTC, pepelyaeva commented on addon/components/fd-view-definition-item.js
Должны отображаться атрибуты мастера
![image](https://user-images.githubusercontent.com/15091209/231084297-c3998f9d-549a-4b86-b32f-b36ef4535c0a.png)

2023-04-11 07:30 UTC, PrographerMan commented on addon/components/fd-view-definition-item.js
> +  selectedPropertyObserver: observer('selectedProperty.lookupType', function() {
`selectedProperty` меняет значение позже, чем срабатывает наблюдатель. На момент срабатывания наблюдателя его значение `undefined`

2023-06-23 11:34 UTC, s-andrey approved these changes

2023-06-23 11:34 UTC, s-andrey commented on addon/components/fd-view-definition-item.js
лучше все это сразу в fd-create-view делать

2023-06-23 12:14 UTC, merged