Add timezone if missing
Flexberry/ember-flexberry-designer pull request #837
Opened 2023-09-29 12:49 UTC by TeterinaSvetlana

2023-09-29 12:49 UTC, AbdullahWins reviewed
Good Job!

2023-10-04 12:36 UTC, AntonIV8 requested changes, later dismissed

2023-10-04 12:36 UTC, AntonIV8 commented on addon/services/fd-current-project-context.js
> +            momentDate._tzm = - new Date().getTimezoneOffset();
тут точно после знака - нужен пробел ?

2023-10-04 13:20 UTC, pepelyaeva approved these changes

2023-10-04 13:33 UTC, merged