Add logic for fix broken diograms
Flexberry/ember-flexberry-designer pull request #858
Opened 2023-10-25 11:55 UTC by s-andrey

2023-10-25 12:30 UTC, bratchikov requested changes

2023-10-25 12:30 UTC, bratchikov commented on addon/locales/ru/components/fd-uml-diagram.js
> +  'message-fix-diagram': 'Исправлены ошибки в ссылках элементов диаграммы на репозитарные объекты, нажмите сохранить чтобы применить изменения',
```suggestion
  'message-fix-diagram': 'Исправлены ошибки в ссылках элементов диаграммы на репозитарные объекты, нажмите кнопку «Сохранить» чтобы применить изменения',
```

2023-10-25 12:30 UTC, bratchikov commented on addon/locales/ru/components/fd-uml-diagram.js
> +  'error-can-not-fix': 'На диаграмме, найдена ошибка, которую, не получается исправить автоматически, битая ссылка у связи {{modelName}} и классов на которые она ссылается {{startClassName}} и {{endC
```suggestion
  'error-can-not-fix': 'На диаграмме, найдена ошибка, которую, не удалось исправить автоматически: неверная ссылка у связи {{modelName}} и классов на которые она ссылается {{startClassName}} и {{endClassName}}'
```

2023-10-25 12:33 UTC, bratchikov approved these changes

2023-10-26 15:13 UTC, pepelyaeva commented on addon/locales/ru/components/fd-uml-diagram.js
> +  'error-not-found-model': 'На диаграмме найдена ошибка в модели {{modelName}} которую, не получается исправить автоматически',
Может так лучше? На диаграмме, в модели {{modelName}}, найдена ошибка, которую не получается исправить автоматически

2023-10-26 15:17 UTC, pepelyaeva commented on addon/locales/ru/components/fd-uml-diagram.js
> +  'error-can-not-fix': 'На диаграмме, найдена ошибка, которую, не удалось исправить автоматически: неверная ссылка у связи {{modelName}} и классов на которые она ссылается {{startClassName}} и {{endC
Много запятых. 'На диаграмме найдена ошибка, которую не удалось исправить автоматически..'

2023-10-27 06:05 UTC, s-andrey commented on addon/locales/ru/components/fd-uml-diagram.js
> +  'error-can-not-fix': 'На диаграмме, найдена ошибка, которую, не удалось исправить автоматически: неверная ссылка у связи {{modelName}} и классов на которые она ссылается {{startClassName}} и {{endC
ворд говорит что так правильно)

2023-10-27 13:46 UTC, pepelyaeva commented on addon/locales/ru/components/fd-uml-diagram.js
> +  'error-not-found-model': 'На диаграмме в модели {{modelName}} найдена ошибка которую, не получается исправить автоматически',
Надо запятую поставить перед 'которую'

2023-10-27 17:01 UTC, bratchikov commented on addon/locales/ru/components/fd-uml-diagram.js
> +  'error-not-found-model': 'На диаграмме в модели {{modelName}} найдена ошибка которую, не получается исправить автоматически',
```suggestion
  'error-not-found-model': 'На диаграмме в модели {{modelName}} найдена ошибка, которую не получается исправить автоматически',
```

2023-10-30 05:42 UTC, merged