Add exitProject button
Flexberry/ember-flexberry-designer pull request #866
Opened 2023-10-30 11:31 UTC by TeterinaSvetlana

2023-11-01 09:35 UTC, AntonIV8 requested changes

2023-11-01 09:35 UTC, AntonIV8 commented on addon/utils/get-user-setting.js
> +  let cp = new SimplePredicate('userName', 'eq', userName);
sp может, или лучше predicate назвать

2023-11-01 09:35 UTC, AntonIV8 commented on addon/utils/get-user-setting.js
> +  let modelName = 'new-platform-flexberry-flexberry-user-setting';
const

2023-11-01 09:35 UTC, AntonIV8 commented on addon/utils/get-user-setting.js
> +  let builder = new Builder(store)
const

2023-11-01 09:35 UTC, AntonIV8 commented on addon/utils/get-user-setting.js
> +      if (isArray(foundRecords) && foundRecords.length > 0) {
а тут toArray хоть на чем может сработать ?

т.е если например в result прийдет string и над ней выполнить toArray, то не упадет ли он.
Если упадет, то if (isArray(foundRecords) наверное не нужно, если toArray либо падает либо точно выдает array

2023-11-01 09:35 UTC, AntonIV8 commented on tests/dummy/app/routes/application.js
> +      let store = this.get('store');
const

2023-11-01 09:35 UTC, AntonIV8 commented on tests/dummy/app/routes/application.js
> +            foundRecord.destroyRecord();
А почему в методе getExistingRecord уничтожаются все, кроме 0, чтобы потом ее тут уничтожить

2023-11-01 09:53 UTC, TeterinaSvetlana commented on tests/dummy/app/routes/application.js
> +            foundRecord.destroyRecord();
тут уничтожается запись для того, что бы при перезагрузке страницы закрытая стадия снова не открылась

2023-11-02 10:10 UTC, AntonIV8 requested changes

2023-11-02 10:10 UTC, AntonIV8 commented on tests/dummy/app/controllers/application.js
> +          this.get('fdSheetService').closeSheet(name);
а вот это зачем ? т.е если на листе есть несохр данные, то его закрываем ? А если нет таких данных

2023-11-02 10:13 UTC, TeterinaSvetlana commented on tests/dummy/app/controllers/application.js
> +          this.get('fdSheetService').closeSheet(name);
да, а если несохраненных нет - закрываем стадию

2023-11-02 10:24 UTC, AntonIV8 approved these changes

2023-11-02 14:41 UTC, merged