Add the ability to create editform/listform via diagram
Flexberry/ember-flexberry-designer pull request #868
Opened 2023-10-31 09:49 UTC by pepelyaeva

2023-10-31 10:31 UTC, AntonIV8 requested changes

2023-10-31 10:31 UTC, AntonIV8 commented on addon/components/fd-editing-panels/fd-listform-editing-panel.js
> +        this.set('viewValue');
А это что значит ?

2023-10-31 10:31 UTC, AntonIV8 commented on addon/components/fd-editing-panels/fd-listform-editing-panel.js
> +        const dataObjectTypes = this.get('model.formViews.firstObject.dataObjectTypes');
А это тут точно const ?

dataObjectTypes.set('editContainerName');
dataObjectTypes.set('newContainerName');

Вот тут ведь что-то в нем вроде устанавливается, или нет ?

2023-10-31 12:36 UTC, pepelyaeva commented on addon/components/fd-editing-panels/fd-listform-editing-panel.js
> +        this.set('viewValue');
Сброс значения, чтобы при смене dataobject чистился выпадающий список с представлениями

2023-10-31 12:52 UTC, pepelyaeva commented on addon/components/fd-editing-panels/fd-listform-editing-panel.js
> +        const dataObjectTypes = this.get('model.formViews.firstObject.dataObjectTypes');
Содержимое объекта можно менять, в переменной ссылка на объект

2023-11-03 09:10 UTC, AntonIV8 approved these changes

2023-11-03 11:26 UTC, s-andrey approved these changes

2023-11-07 08:04 UTC, merged